trigger:
- master

pr:
- master

stages:
- stage: Tests
  jobs:
  - job: macOS
    pool:
      vmImage: 'macOS-latest'
    steps:
    - checkout: self

    - script: |
        echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_11.4.app;
        sudo xcode-select --switch /Applications/Xcode_11.4.app/Contents/Developer
    - script: |
        msbuild ./test-project/test-project.csproj /t:build /p:configuration=debug;platform=iPhoneSimulator
